/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=AskPavaoEnv worker/env.d.ts` (hash: c24cc9a0f6d12fb415167e323b76db2f)
interface __BaseEnv_AskPavaoEnv {
	ASK_PAVAO_EMAIL: SendEmail;
	ASK_PAVAO_LIMITER: RateLimit;
	APP_ORIGIN: string;
	TURNSTILE_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_AskPavaoEnv {}
}
interface AskPavaoEnv extends __BaseEnv_AskPavaoEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "TURNSTILE_SECRET_KEY">> {}
}
